version: "3"
services: 
  redis:
     image: redis
     ports: 
     - "6379:6379"
  joke: 
     build: 
      context: ./
      dockerfile: ./Dockerfile-joke
     ports: 
     - "1223:1223"
  godns: 
     build: 
      context: ./
      dockerfile: ./Dockerfile-godns
     ports: 
     - "53:53/udp"
     - "53:53/tcp"