version: "3"
services:
   redis:
      image: redis
      ports:
         - "6379:6379"
      networks:
         service1_net:
            ipv4_address: 192.168.1.2
   joke:
      image: dalongrong/godns:joke
      build:
         context: ./
         dockerfile: ./Dockerfile-joke
      networks:
         service1_net:
            ipv4_address: 192.168.1.3
      ports:
         - "1223:1223"
   godns:
      image: dalongrong/godns
      build:
         context: ./
         dockerfile: ./Dockerfile-godns
      networks:
         service1_net:
            ipv4_address: 192.168.1.4
   coredns:
      image: coredns/coredns:1.7.0
      networks:
         service1_net:
            ipv4_address: 192.168.1.5
      volumes:
         - "./Corefile:/opt/Corefile"
      command: -conf /opt/Corefile
      ports:
         - "53:53/udp"
         - "53:53/tcp"
networks:
   service1_net:
      ipam:
         driver: default
         config:
            - subnet: 192.168.1.0/16
